language: node_js
node_js:
  - '9'

cache:
  cache: yarn
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- -- version 0.23.2
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

before_script:

script:
  - yarn docs:build

after_script:
  - cd ./dist
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "deploy"
  - git push --force --quiet "https://${GH_PAGES_TOKEN}@${GH_REF}" master:${P_BRANCH}

branches:
  only:
    - master
# env:
#  global:
#    - GH_REF: github.com/ohhoney1/Vue.js-Source-Code-line-by-line
